language: php

php:
  - 7.0.21
  - 7.1

before_script:
  - cp .env.travis .env
  - mysql -e 'create database testing;'
  - composer self-update
  - composer install --dev --prefer-source --no-interaction
  - travis_retry php artisan key:generate
  - travis_retry php artisan migrate
  - . $HOME/.nvm/nvm.sh
  - nvm install 6.10.3
  - nvm use 6.10.3
  - npm install -g yarn
  - yarn
  - yarn run production

env:
  global:
    - setup=basic

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
    - travis_retry composer self-update

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-dist --no-suggest; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi

script:
  - vendor/bin/phpunit --debug
